[server]
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#00539B"
backgroundColor = "#f5f8f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#16202a"
font = "sans serif"
